### ISSUE TITLE
Some Serious Issues

### ISSUE THREAD

**Issue by TheMaddog** [paully104/ReitzRPG#1]
Hi there, this is the holy plugin that I need for my server.

Unfortunately I cannot use it because;

A: .16-Alpha: ReitzRPG for CB 1.7.9-R0.2 Jul 31, 2014
Monsters Freeze on Death

A: .15-Alpha: ReitzRPG for CB 1.7.9-R0.2 Jul 24, 2014
Monsters Freeze on Death

B: .14-Beta: ReitzRPG for CB 1.7.9-R0.1 Jul 18, 2014
A player does not get Combat XP even OPs do not get Combat XP when killing a monster.

A: .14-Alpha: ReitzRPG for CB 1.7.9-R0.1 Jul 16, 2014
Monsters Freeze on Death

B: .13-Beta: ReitzRPG for CB 1.7.9-R0.1 Jul 12, 2014
A player does not get Combat XP even OPs do not get Combat XP when killing a monster.

It appears that the BETAs work but the players do not get XP and it appears that the Alphas work but monsters freeze for 1 second on death.

Here's my server log;

[18:57:17] [Server thread/INFO]: Starting minecraft server version 1.7.10
[18:57:17] [Server thread/INFO]: Loading properties
[18:57:17] [Server thread/INFO]: Default game type: SURVIVAL
[18:57:17] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-1.7.9-R0.2-207-g03373bb (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT)
[18:57:18] [Server thread/INFO]: Using 4 threads for Netty based IO
[18:57:18] [Server thread/INFO]: Server Ping Player Sample Count: 12
[18:57:18] [Server thread/INFO]: Debug logging is disabled
[18:57:18] [Server thread/INFO]: Generating keypair
[18:57:18] [Server thread/INFO]: Starting Minecraft server on _:25565
[18:57:19] [Server thread/INFO]: Set PluginClassLoader as parallel capable
[18:57:19] [Server thread/INFO]: [WorldEdit] Loading WorldEdit v5.6.3
[18:57:19] [Server thread/INFO]: [SerialKey] Loading SerialKey v0.2.1
[18:57:19] [Server thread/INFO]: [PorteCoulissante] Loading PorteCoulissante v1.4.3
[18:57:19] [Server thread/INFO]: [Quests] Loading Quests v1.9.0
[18:57:19] [Server thread/INFO]: [Vault] Loading Vault v1.4.1-b436
[18:57:19] [Server thread/INFO]: [ProtocolLib] Loading ProtocolLib v3.4.0
[18:57:19] [Server thread/WARN]: [ProtocolLib] Version (MC: 1.7.10) has not yet been tested! Proceed with caution.
[18:57:20] [Server thread/INFO]: [PermissionsEx] Loading PermissionsEx v1.22.5
[18:57:20] [Server thread/INFO]: [WorldGuard] Loading WorldGuard v6.0.0-beta-02
[18:57:20] [Server thread/INFO]: [ReitzRPG] Loading ReitzRPG v1.0
[18:57:20] [Server thread/INFO]: [dynmap] Loading dynmap v2.0.0-SNAPSHOT-1047
[18:57:20] [Server thread/INFO]: [dynmap] version=git-Spigot-1.7.9-R0.2-207-g03373bb (MC: 1.7.10)
[18:57:20] [Server thread/INFO]: [dynmap] Mod Support API available
[18:57:20] [Server thread/INFO]: [Essentials] Loading Essentials vPre2.14.1.3
[18:57:20] [Server thread/INFO]: [ItemRules] Loading ItemRules v1.0.10
[18:57:20] [Server thread/INFO]: [GoldToCash] Loading GoldToCash v2.3
[18:57:20] [Server thread/INFO]: [Citizens] Loading Citizens v2.0.13-SNAPSHOT (build 1178)
[18:57:20] [Server thread/INFO]: [EssentialsSpawn] Loading EssentialsSpawn vPre2.14.1.3
[18:57:20] [Server thread/INFO]: [Sentry] Loading Sentry v1.8.2
[18:57:20] [Server thread/INFO]: [EssentialsChat] Loading EssentialsChat vPre2.14.1.3
[18:57:20] [Server thread/INFO]: [Brewery] Loading Brewery v1.3
[18:57:20] [Server thread/INFO]: [dtlTraders] Loading dtlTraders v3.1.0-snapshot
[18:57:20] [Server thread/INFO]: [Vault] Enabling Vault v1.4.1-b436
[18:57:20] [Server thread/INFO]: [Vault] [Economy] Essentials Economy found: Waiting
[18:57:20] [Server thread/INFO]: [Vault] [Permission] PermissionsEx found: Waiting
[18:57:20] [Server thread/INFO]: [Vault] [Permission] SuperPermissions loaded as backup permission system.
[18:57:20] [Server thread/INFO]: [Vault] [Chat] PermissionsEx found: Waiting
[18:57:20] [Server thread/INFO]: [Vault] Enabled Version 1.4.1-b436
[18:57:20] [Server thread/INFO]: [ProtocolLib] Enabling ProtocolLib v3.4.0
[18:57:20] [Server thread/INFO]: [ProtocolLib] Started structure compiler thread.
[18:57:20] [Server thread/INFO]: *_*\* Beginning UUID conversion, this may take A LONG time ****
[18:57:20] [Server thread/INFO]: Preparing level "world"
[18:57:20] [Server thread/INFO]: -------- World Settings For [world] --------
[18:57:20] [Server thread/INFO]: Mob Spawn Range: 4
[18:57:20] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[18:57:20] [Server thread/INFO]: Cactus Growth Modifier: 100%
[18:57:20] [Server thread/INFO]: Cane Growth Modifier: 100%
[18:57:20] [Server thread/INFO]: Melon Growth Modifier: 100%
[18:57:20] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[18:57:20] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[18:57:20] [Server thread/INFO]: Sapling Growth Modifier: 100%
[18:57:20] [Server thread/INFO]: Wheat Growth Modifier: 100%
[18:57:20] [Server thread/INFO]: Anti X-Ray: false
[18:57:20] [Server thread/INFO]:    Engine Mode: 1
[18:57:20] [Server thread/INFO]:    Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
[18:57:20] [Server thread/INFO]:    Replace Blocks: [1, 5]
[18:57:20] [Server thread/INFO]: Entity Activation Range: An 32 / Mo 32 / Mi 16
[18:57:20] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[18:57:20] [Server thread/INFO]: Alternative Hopper Ticking: false
[18:57:20] [Server thread/INFO]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[18:57:20] [Server thread/INFO]: Random Lighting Updates: false
[18:57:20] [Server thread/INFO]: Structure Info Saving: true
[18:57:20] [Server thread/INFO]: Sending up to 5 chunks per packet
[18:57:20] [Server thread/INFO]: Max Entity Collisions: 8
[18:57:20] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[18:57:20] [Server thread/INFO]: Max TNT Explosions: 100
[18:57:20] [Server thread/INFO]: View Distance: 6
[18:57:20] [Server thread/INFO]: Chunks to Grow per Tick: 650
[18:57:20] [Server thread/INFO]: Clear tick list: false
[18:57:20] [Server thread/INFO]: Experience Merge Radius: 3.0
[18:57:20] [Server thread/INFO]: Item Despawn Rate: 6000
[18:57:20] [Server thread/INFO]: Item Merge Radius: 2.5
[18:57:20] [Server thread/INFO]: Arrow Despawn Rate: 1200
[18:57:20] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[18:57:20] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[18:57:20] [Server thread/INFO]: Preparing start region for level 0 (Seed: -42494964244591)
[18:57:21] [Server thread/INFO]: Preparing spawn area: 41%
[18:57:22] [Server thread/INFO]: [WorldEdit] Enabling WorldEdit v5.6.3
[18:57:22] [Server thread/INFO]: WEPIF: Using the Bukkit Permissions API.
[18:57:22] [Server thread/INFO]: [SerialKey] Enabling SerialKey v0.2.1
[18:57:22] [Server thread/INFO]: [PorteCoulissante] Enabling PorteCoulissante v1.4.3
[18:57:22] [Server thread/INFO]: [PorteCoulissante] SpoutPlugin not available; disabling sound effects
[18:57:22] [Server thread/INFO]: [PorteCoulissante] Plugin version 1.4.3 by Captain_Chaos enabled
[18:57:22] [Server thread/INFO]: [Quests] Enabling Quests v1.9.0
[18:57:22] [Server thread/INFO]: [Quests] Enabled.
[18:57:22] [Server thread/INFO]: [PermissionsEx] Enabling PermissionsEx v1.22.5
[18:57:22] [Server thread/INFO]: [PermissionsEx] Initializing file backend
[18:57:22] [Server thread/INFO]: [PermissionsEx] Permissions file successfully reloaded
[18:57:22] [Server thread/INFO]: WEPIF: PermissionsEx detected! Using PermissionsEx for permissions.
[18:57:22] [Server thread/INFO]: [Vault][Permission] PermissionsEx hooked.
[18:57:22] [Server thread/INFO]: [Vault][Chat] PermissionsEx_Chat hooked.
[18:57:22] [Server thread/INFO]: [WorldGuard] Enabling WorldGuard v6.0.0-beta-02
[18:57:23] [Server thread/INFO]: [WorldGuard](world) TNT ignition is blocked.
[18:57:23] [Server thread/INFO]: [WorldGuard](world) Lighters are PERMITTED.
[18:57:23] [Server thread/INFO]: [WorldGuard](world) Lava fire is blocked.
[18:57:23] [Server thread/INFO]: [WorldGuard](world) All fire spread is disabled.
[18:57:23] [Server thread/INFO]: [WorldGuard] Loaded configuration for world 'world'
[18:57:23] [Server thread/INFO]: [WorldGuard] Loading region data...
[18:57:23] [Server thread/INFO]: [ReitzRPG] Enabling ReitzRPG v1.0
[18:57:23] [Server thread/INFO]: [ReitzRPG] ReitzRPG is now enabled
[18:57:23] [Server thread/INFO]: Persistance is happening
[18:57:23] [Server thread/INFO]: [dynmap] Enabling dynmap v2.0.0-SNAPSHOT-1047
[18:57:23] [Thread-8/INFO]: [Skyupdater] No update found for 'SerialKey'.
[18:57:23] [Server thread/INFO]: [dynmap] Using PermissionsEx 1.22.5 for access control
[18:57:24] [Server thread/INFO]: [dynmap] Mod Support processing completed
[18:57:25] [Server thread/INFO]: [dynmap] Loaded 23 shaders.
[18:57:25] [Server thread/INFO]: [dynmap] Loaded 82 perspectives.
[18:57:25] [Server thread/INFO]: [dynmap] Loaded 12 lightings.
[18:57:25] [Server thread/INFO]: [dynmap] Web server started on address 0.0.0.0:8123
[18:57:25] [Server thread/INFO]: [dynmap] version 2.0.0-SNAPSHOT-1047 is enabled - core version 2.0.0-SNAPSHOT-1992
[18:57:25] [Server thread/INFO]: [dynmap] Loaded 3 maps of world 'world'.
[18:57:25] [Server thread/INFO]: [dynmap] Loaded 8 pending tile renders for world 'world'
[18:57:26] [Server thread/INFO]: [dynmap] Enabled
[18:57:26] [Server thread/INFO]: [Essentials] Enabling Essentials vPre2.14.1.3
[18:57:26] [Server thread/INFO]: Bukkit version format changed. Version not checked.
[18:57:26] [Server thread/INFO]: git-Spigot-1.7.9-R0.2-207-g03373bb (MC: 1.7.10)
[18:57:26] [Server thread/INFO]: 1.7.10-R0.1-SNAPSHOT
[18:57:26] [Server thread/INFO]: Using locale en_US
[18:57:26] [Server thread/INFO]: Using locale en_US
[18:57:26] [Server thread/INFO]: [Vault][Economy] Essentials Economy hooked.
[18:57:26] [Server thread/INFO]: Essentials: Using PermissionsEx based permissions.
[18:57:26] [Server thread/INFO]: [ItemRules] Enabling ItemRules v1.0.10
[18:57:26] [Server thread/INFO]: Vault integration for [ItemRules] is enabled
[18:57:26] [Server thread/INFO]: Factions integration for [ItemRules] not enabled
[18:57:26] [Server thread/INFO]: mcMMO integration for [ItemRules] is not enabled
[18:57:26] [Server thread/INFO]: ItemRules loaded 5 rules total.
[18:57:26] [Server thread/INFO]: [GoldToCash] Enabling GoldToCash v2.3
[18:57:26] [Server thread/INFO]: [GoldToCash] Vault Economy loaded with success !
[18:57:26] [Server thread/INFO]: [Citizens] Enabling Citizens v2.0.13-SNAPSHOT (build 1178)
[18:57:26] [Server thread/ERROR]: [Citizens] Unable to find Rhino classes - javascript scripts won't see non-CraftBukkit classes
[18:57:27] [Server thread/INFO]: [EssentialsSpawn] Enabling EssentialsSpawn vPre2.14.1.3
[18:57:27] [Server thread/INFO]: [Sentry] Enabling Sentry v1.8.2
[18:57:27] [Server thread/INFO]: [Sentry] Could not register with Denizen
[18:57:27] [Server thread/INFO]: [Sentry] Could not find or register with Towny
[18:57:27] [Server thread/INFO]: [Sentry] Could not find or register with Factions.
[18:57:27] [Server thread/INFO]: [Sentry] Could not find or register with War. 
[18:57:27] [Server thread/INFO]: [Sentry] Could not find or register with SimpleClans. 
[18:57:27] [Server thread/INFO]: [EssentialsChat] Enabling EssentialsChat vPre2.14.1.3
[18:57:27] [Server thread/INFO]: [Brewery] Enabling Brewery v1.3
[18:57:27] [Server thread/INFO]: [0;32;22m[Brewery] [0;37;1mBrewery enabled![m
[18:57:27] [Server thread/INFO]: [dtlTraders] Enabling dtlTraders v3.1.0-snapshot
[18:57:27] [Server thread/INFO]: [dtlTraders][0;37;1m[INFO] Economy plugin: [0;33;1mEssentials Economy[m
[18:57:27] [Server thread/INFO]: [dtlTraders][0;37;1m[INFO] Loading config files[m
[18:57:27] [Server thread/INFO]: [dtlTraders][0;37;1m[INFO] Registered core attributes: [0;37;1m[[0;33;1mGenericDamage[m ,[0;33;1mPatternItem[m ,[0;33;1mName[m ,[0;33;1mBook[m ,[0;33;1mSkull[m ,[0;33;1mSlot[m ,[0;33;1mStoredEnchants[m ,[0;33;1mGenericKnockback[m ,[0;33;1mPotion[m ,[0;33;1mMultiplier[m ,[0;33;1mEnchants[m ,[0;33;1mDurability[m ,[0;33;1mGenericSpeed[m ,[0;33;1mGenericHealth[m ,[0;33;1mPrice[m ,[0;33;1mAmount[m ,[0;33;1mLeather color[m ,[0;33;1mLimit[m ,[0;33;1mTier[m ,[0;33;1mFirework[m[0;37;1m][m
[18:57:27] [Server thread/INFO]: [dtlTraders][0;37;1m[INFO] Registered core flags: [0;37;1m[[0;33;1mLore[m ,[0;33;1mNoStack[m ,[0;33;1mAbstract[m ,[0;33;1mAnylore[m ,[0;33;1mSplashPotion[m ,[0;33;1mStackPrice[m ,[0;33;1mDataCheck[m ,[0;33;1mRegex[m[0;37;1m][m
[18:57:27] [Server thread/INFO]: [dtlTraders][0;37;1m[INFO] Registered types: [0;37;1m[[0;33;1mserver[m[0;37;1m][m
[18:57:27] [Server thread/INFO]: [dtlTraders][0;37;1m[INFO] Permission plugin: [0;33;1mPermissionsEx[m
[18:57:27] [Server thread/INFO]: [dtlTraders][0;37;1m[INFO] Accounts loaded: [0;33;1m0[m
[18:57:27] [Server thread/INFO]: [dtlTraders][0;37;1m[INFO] Enabled[m
[18:57:27] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[18:57:28] [Server thread/INFO]: Done (7.833s)! For help, type "help" or "?"
[18:57:28] [Server thread/INFO]: [Sentry] Registered sucessfully with Vault: 2 groups found. The GROUP: target will function
[18:57:31] [Server thread/INFO]: [Citizens] Loaded 28 NPCs.
[18:57:32] [Dynmap Render Thread/INFO]: [dynmap] Loading default resource pack
[18:57:32] [Server thread/ERROR]: [Quests] npc-giver-id: for Quest Zombie Test is not a valid NPC id!
[18:57:32] [Server thread/INFO]: [Quests] 3 Quest(s) loaded.
[18:57:32] [Server thread/INFO]: [Quests] 5 Event(s) loaded.
[18:57:32] [Server thread/INFO]: [Quests] 813 Phrase(s) loaded.

When the monster is killed the monster freezes in the spot and as soon as it unfreezes and dies the table at the right of the screen with all the skills updates with a new value.

I really hope you can fix this for us, this plugin has everything I need, thank you.

**Comment by paully104** [comment]
​Would you mind toying around with this build? I've been working on the next update and been doing various requests and other fixes. Im trying to pinpoint the reason the monsters freeze on death, it only happens in spigot.

https://dl.dropboxusercontent.com/u/33869140/ReitzRPG.jar

**Comment by TheMaddog** [comment]
Thank you Paul, I'll give that a try.

**Comment by TheMaddog** [comment]
I got my hopes up that this would fix the issues. However The monsters lag the entire server when they are killed but everything else works fine ..

There is a minor issue where monsters sometimes do not have their names and levels above their head but honestly not to be crude I couldn't care less, I'd just like the plugin to not lag the server. It's perfect and has absolutely everything I need. It's been a week of stress, trying to find an RPG class system with the ability to create custom items and have the monsters levels increase the further the player is from the world spawn ? Perfect!!

If you'd like to know I'm trying to bring WoW gameplay to Minecraft, it's just so you have an understanding of what i'm working on and simply without your plugin the end product of my server will be total crap .. I just know it.

http://www.themaddogsworld.info/wiki/index.php?title=Minecraft_Home

[22:11:15] [Server thread/ERROR]: Could not pass event EntityDeathEvent to ReitzRPG v1.0
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-patched.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-patched.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:509) [spigot-patched.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:494) [spigot-patched.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:379) [spigot-patched.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.EntityLiving.die(EntityLiving.java:810) [spigot-patched.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.EntitySkeleton.die(EntitySkeleton.java:123) [spigot-patched.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.EntityLiving.damageEntity(EntityLiving.java:745) [spigot-patched.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.EntityMonster.damageEntity(EntityMonster.java:48) [spigot-patched.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.EntityHuman.attack(EntityHuman.java:950) [spigot-patched.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:1204) [spigot-patched.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:37) [spigot-patched.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.PacketPlayInUseEntity.handle(PacketPlayInUseEntity.java:49) [spigot-patched.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:186) [spigot-patched.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [spigot-patched.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [spigot-patched.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot-patched.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot-patched.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot-patched.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot-patched.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
Caused by: java.lang.NullPointerException
    at com.paulreitz.reitzrpg.DistanceLevel.onMobDeath(DistanceLevel.java:622) ~[?:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_65]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_65]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_65]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_65]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[spigot-patched.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    ... 19 more
[22:11:24] [Server thread/ERROR]: Could not pass event EntityDeathEvent to ReitzRPG v1.0
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-patched.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-patched.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:509) [spigot-patched.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:494) [spigot-patched.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:379) [spigot-patched.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.EntityLiving.die(EntityLiving.java:810) [spigot-patched.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.EntityLiving.damageEntity(EntityLiving.java:745) [spigot-patched.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.EntityMonster.damageEntity(EntityMonster.java:48) [spigot-patched.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.EntityHuman.attack(EntityHuman.java:950) [spigot-patched.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:1204) [spigot-patched.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:37) [spigot-patched.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.PacketPlayInUseEntity.handle(PacketPlayInUseEntity.java:49) [spigot-patched.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:186) [spigot-patched.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [spigot-patched.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [spigot-patched.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot-patched.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot-patched.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot-patched.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot-patched.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
Caused by: java.lang.NullPointerException
    at com.paulreitz.reitzrpg.DistanceLevel.onMobDeath(DistanceLevel.java:622) ~[?:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_65]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_65]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_65]
    at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_65]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[spigot-patched.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    ... 18 more

**Comment by paully104** [comment]
​I'm looking into it to be honest i noticed the issue about a 2-3 weeks ago but it only happens with the spigot servers and i re-evaluated my code and couldn't find a solution. Im still going to toy around with it and see what can be done but ill probably have to go on the spigot forums and figure out why it is happening.

**Comment by TheMaddog** [comment]
Paully if you need root access to a dedicated Minecraft server you're most welcome to use it. I've added you on Skype, please let me know.

**Comment by TheMaddog** [comment]
Perhaps the answer is inside 1 of the BETAs. When monsters die in the beta versions they don't lag ... But the issue with the BETAs is that I don't get XP. The Alphas I do get XP but the monsters lag.

**Comment by paully104** [comment]
Which beta? 

Sent via the Samsung GALAXY S® 5, an AT&T 4G LTE smartphone

-------- Original message --------

**Comment by TheMaddog** [comment]
Sorry for the late reply i've been busy.

All betas listed at the top don't lag but don't give XP. The alphas they lag and give XP ... they work but unusable for a public server

**Comment by paully104** [comment]
Issues should be resolved!
